parameters:
  hk47196.oidcprovider.access_table: 'oauth2_access_token'
  hk47196.oidcprovider.auth_code_table: 'oauth2_authorization_code'
  hk47196.oidcprovider.refresh_token_table: 'oauth2_refresh_token'